### PR TITLE
Fixing restart problem

### PR DESCRIPTION
**Pull request by alexlanz**

### CODE REVIEW

**Comment by Piiit** [comment]
@alexlanz I do not understand this fix, can you provide some info? Possibly also during our next call.

**Comment by alexlanz** [comment]
Sure, I can explain it to you the next time. But basically, the containers are not restarting as expected when you `docker-compose stop` them. To fix it, we had to perfrom a `docker-compose down` so that the containers are deleted completely and created newly from scratch with `docker-compose up -d`.

**Comment by Piiit** [comment]
@alexlanz OK, thanks... I merge it meanwhile

**Comment by Piiit** [comment]
...and deploy it on testingmachine

**Pull request merged**
